using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TCEntities
{
    public partial class Patient22
    {
        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public long PatientKey { get; set; }
        //public List<NoteData> ClinicalNotes = null;
        //public List<NoteData> NonClinicalNotes = null;
        //public List<NoteData> NoteList { get; set; }
        //public List<NoteData> TherapyScheduleNotes = null;
        //public long Account { get; set; }
        //public string ACReceived { get; set; }
        //public string ActiveDate { get; set; }
        //public string Added { get; set; }
        //public string AddedBy { get; set; }
        public string Address1 { get; set; }
        //public string Address2 { get; set; }
        ////public string Age { get; set; }
        //public string Allergy1 { get; set; }
        //public string Allergy2 { get; set; }
        //public string Allergy3 { get; set; }
        //public string Allergy4 { get; set; }
        //public string Authorization1 { get; set; }
        //public string BestDay { get; set; }
        //public string BestTime { get; set; }
        //public string BillingInstructions { get; set; }
        //public string BillingRep { get; set; }
        //public string CallRefills { get; set; }
        //public string CardMemberID { get; set; }
        //public string Caremark { get; set; }
        //public string CaremarkKey { get; set; }
        //public string CCBSDate { get; set; }
        //public string CellPhone { get; set; }
        public string City { get; set; }
        //public string ClaimsAddress { get; set; }
        //public string ClientPatientKey { get; set; }
        //public string ClinicalDate { get; set; }
        //public string ClinicalLocation { get; set; }
        //public string ClinicalTrialPatient { get; set; }
        //public string CNSS { get; set; }
        //public string CNSSDate { get; set; }
        //public string Comment1 { get; set; }
        //public string Comment2 { get; set; }
        //public string CountryCode { get; set; }
        //public string CTCaseTag { get; set; }
        //public string Discharged { get; set; }
        //public string DispenseDate { get; set; }
        ////public int DistLocationKey { get; set; }
        //public string DOB { get; set; }
        //public string DoNotCallPatient { get; set; }
        //public string DRCID { get; set; }
        //public long DrKey1 { get; set; }
        //public long DrKey2 { get; set; }
        //public string DrugCode { get; set; }
        //public string ECHODate { get; set; }
        //public string Email { get; set; }
        //public string EnrollStatus { get; set; }
        //public long Fake1 { get; set; }
        //public long Fake2 { get; set; }
        //public long Fake3 { get; set; }
        //public string Fax { get; set; }
        public string FirstName { get; set; }
        //public string FollowupDate { get; set; }
        //public string Frequency { get; set; }
        //public string HCVgenotype { get; set; }
        //public string HealthBridgeID { get; set; }
        //public string Height { get; set; }
        //public string HIPAARefuse { get; set; }
        //public string HIPPAConsentDate { get; set; }
        //public string HIPPAExpDate { get; set; }
        //public string HPDate { get; set; }
        //public string HSeeNotes { get; set; }
        //public string IjtReason { get; set; }
        //public string InactiveDate { get; set; }
        //public string Infusion { get; set; }
        //public string IniCall { get; set; }
        //public string IsFemaleCB { get; set; }
        //public string LabSync { get; set; }
        //public string LabSyncDate { get; set; }
        //public string LastModifiedBy { get; set; }
        //public string LastModifiedDate { get; set; }
        public string LastName { get; set; }
        //public string LeaveMsg { get; set; }
        //public string Letter { get; set; }
        //public string LetterDate { get; set; }
        //public string Lifetime { get; set; }
        //public string ManagingDrCheck { get; set; }
        //public string ManagingDrDate { get; set; }
        //public string MeanPAP { get; set; }
        //public long MedBenPayerKeyFake1 { get; set; }
        //public long MedBenPayerKeyFake2 { get; set; }
        //public long MedBenPayerKeyFake3 { get; set; }
        //public string MI { get; set; }
        //public string MrktRsrch { get; set; }
        //public string NextDueDate { get; set; }
        //public string NotesRecord { get; set; }
        //public string NoticeSent { get; set; }
        //public string OgsReason { get; set; }
        //public string OnePathCasemgr { get; set; }
        //public string OptOut { get; set; }
        //public string OptOutDate { get; set; }
        //public string OtherAllergies { get; set; }
        //public string OtherFrequency { get; set; }
        //public string OverrideRep { get; set; }
        //public string PANDate { get; set; }
        //public string ParentGuardianName { get; set; }
        //public string PatActive { get; set; }
        public string PatientName { get; set; }
        ////public string PatientStatusAddedBy { get; set; }
        //public string PatWantDate { get; set; }
        //public string PendingDate { get; set; }
        //public string PerDiemCharge { get; set; }
        //public string PerDiemCode { get; set; }
        ////public string PerDiemDescription { get; set; }
        //public string PerDiemPayer { get; set; }
        //public string PharmacareKey { get; set; }
        //public string PharmacistAssignedTo { get; set; }
        public string Phone1 { get; set; }
        //public string Phone2 { get; set; }
        //public string PhoneNotes { get; set; }
        //public string PhoneRefused { get; set; }
        //public string PlaceofService { get; set; }
        //public string PreferredPhone { get; set; }
        //public string Pregnant { get; set; }
        //public string PregnantReportedDate { get; set; }
        //public string PreviousTBTestDate { get; set; }
        //public string Priority { get; set; }
        //public long RandomPatientKey { get; set; }
        //public string ReceivedConsent { get; set; }
        //public string ReceivedConsentBy { get; set; }
        //public string RefDate { get; set; }
        //public string ReferralReason { get; set; }
        //public string ReferralSource { get; set; }
        //public string RefType { get; set; }
        //public string RefuseDate { get; set; }
        //public string RefusedDoctorInfo { get; set; }
        //public string RefusedDoctorInfoDate { get; set; }
        //public string ReimbCaseMgrAssignedTo { get; set; }
        //public string ReimbLocation { get; set; }
        //public string ReimbursDate { get; set; }
        //public string Reimbursement { get; set; }
        ////public int ReturnKey { get; set; }
        //public string RHCDate { get; set; }
        //public string RnTransfer { get; set; }
        //public string RnTrnsfrReason { get; set; }
        //public string RxPatient { get; set; }
        //public string Sample { get; set; }
        //public string SecondaryDrCheck { get; set; }
        //public string SecondaryDrDate { get; set; }
        //public string Sex { get; set; }
        //public string SigRequired { get; set; }
        //public string SMNDate { get; set; }
        //public string SocSec { get; set; }
        //public string SpecialtyPharmacyID { get; set; }
        //public string SPOCGATCFID { get; set; }
        //public string SRFFxDaysSupply { get; set; }
        ////public int SRFRxRefills { get; set; }
        //public string SRFRxVialsNum { get; set; }
        public string State { get; set; }
        //public string Status { get; set; }
        //public string StatusReason { get; set; }
        //public string SuccessID { get; set; }
        //public string Suffix { get; set; }
        //public string SurveySent { get; set; }
        //public string TaperLetterOAF { get; set; }
        //public string TaperLetterOAF2 { get; set; }
        //public string TaperLetterSentDate { get; set; }
        //public string TaperLetterTM2 { get; set; }
        //public string TCRecvd { get; set; }
        //public string TheraCom { get; set; }
        //public string TherapyAldurazyme { get; set; }
        //public string TherapyCeredase { get; set; }
        //public string TherapyCerezyme { get; set; }
        //public string TherapyFabrazyme { get; set; }
        //public string TherapyFlolan { get; set; }
        //public string TherapyMyozyme { get; set; }
        //public string TherapyRemodulin { get; set; }
        //public string TherapyTracleer { get; set; }
        //public string Title { get; set; }
        //public string TMDuedays { get; set; }
        //public string TreatmentDate { get; set; }
        //public string TreatmentType { get; set; }
        //public string TypeofLetterSent { get; set; }
        ////public string UpdatePatientStatus { get; set; }
        //public string Weight { get; set; }
        //public string WelcomeLetter { get; set; }
        //public string WSeeNotes { get; set; }
        public string Zip { get; set; }
    }
}
